spring.application.name=EurekaClient

server.port=8086

eureka.instance.prefer-ip-address=true

#use true when you are running Eureka client
eureka.client.fetch-registry=true

#use true when you are running Eureka client
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone= http://localhost:9099/eureka
